apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nour0/evnement_kubernetes:latest  # Correct image name and tag
          ports:
            - containerPort: 5001
